# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RSFormViewVanillaExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RSFormViewTester
  pod 'RSFormView', :path => '../'

  target 'RSFormViewVanillaExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RSFormViewVanillaExampleUITests' do
    # Pods for testing
  end

end
